name: planner_mobile_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_simple_dependency_injection: ^2.0.0
  flutter_dotenv: ^5.1.0
  collection: ^1.17.2
  no_context_navigation: ^3.0.0
  adaptive_theme: ^3.4.0
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  modal_bottom_sheet: ^2.1.2
  logger: ^2.0.2
  dio: ^5.3.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/fonts

  fonts:
    - family: 'SFProDisplay'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf
          style: italic
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          style: italic
          weight: 700